### ISSUE TITLE
Support for filter by words?

### ISSUE THREAD

**Issue by MavisCelus19201** [chylex/Discord-History-Tracker#149]
On Discord I often have to search for things by word, I don't know if this can already do that, so "from:user#0000 Apple" and finds all the times Apple came up for an example, I heard mention of it having a search bar but couldn't find it, maybe that's something that could come in the future if possible?

**Comment by AwayJob** [comment]
Yes, I want a search feature too

**Comment by chylex** [comment]
There is a filter option, but you can only pick one type of filter (i.e. either search by author, or by message contents). If you want something more complex, the app creates a SQLite database that you can open in a database program (such as DB Browser for SQLite).

**Comment by chylex** [comment]
Recent versions of the app have filters for date/channels/users that can also be combined with the viewer filters (such as searching for specific words).

I consider this issue resolved since it's possible to do what you asked using features in the app and the viewer, but if you'd still prefer a Discord-style search, I can accept a PR that adds this functionality into the viewer.
