### ISSUE TITLE
"Seed" support?

### ISSUE THREAD

**Issue by TheTechRobo** [chylex/Discord-History-Tracker#157]
I mean, read only access.

So, I could host my DHT (desktop app ofc) on a server, and while the users would write to their own file, the data would be READ (i.e. settings like "When reaching a previously saved message") from the server. That would help stop duplicate data if there was ever a coordinated archive or something.

Is this feasible? Thanks!

**Comment by chylex** [comment]
DHT is strictly local, it will never communicate with the internet. If you want this kind of functionality, you could build your own version of DHT, but I cannot say how feasible it is.

If your use case is a coordinated archive with trusted members, then there are some minor issues with the embeds and emoji reactions that I need to fix before you can safely merge multiple databases into one, but that'll be a simple change (and something I should have tested earlier, since this is a use case I want to support).

**Comment by TheTechRobo** [comment]
Thanks!

**Comment by chylex** [comment]
The next update will have a 'Merge with Database(s)...' button that lets you select any amount of databases and merge them into the currently opened one. Not sure if it's helpful for your particular use case, but it was needed for feature parity with the browser-only version of DHT anyway.

The issues I mentioned with embeds and emoji reactions would have applied for manual merging via SQL, but the app already handles them (mostly) correctly so I figured it's better to just add it directly into the app.

---

In case of interest - the edge case is when two databases have the same message, but from different points in time with different emoji reactions (and technically embeds too, but all you can do with embeds after sending the message is remove them which I suspect is pretty rare).

DHT doesn't store the time a message was captured, so it's not possible to determine which database is more up-to-date. Not an issue when re-tracking old messages since you're always tracking in the present, but a potential problem when merging older databases.

I don't think it's worth adding complexity for this edge case, since the only way to get always-up-to-date emoji reactions is to repeatedly re-track messages in case someone reacts to an older one... so I'm not too worried about it.

**Comment by TheTechRobo** [comment]
Would it be smart to store the time it was captured anyway?

**Comment by TheTechRobo** [comment]
Would it be smart to store the time it was captured anyway?

**Comment by TheTechRobo** [comment]
Sorry - guthib had 500 errors, thats why there's 3 of the same

**Comment by chylex** [comment]
I'm not planning to unless there is a major reason to do so later.
