### ISSUE TITLE
Small, quality of life features for the desktop app

### ISSUE THREAD

**Issue by Neo-Desktop** [chylex/Discord-History-Tracker#165]
While I could probably implement these in a PR, I figure it's best to open a ticket about it first

a) the version of the currently running app is nowhere to be seen in the app - I had to restart it to find out what version I'm running and if I needed to update
  - this could be fixed if the app automatically checks for updates, but that's a more of a big feature

b) it would also be great to see, at a glance, what file is currently loaded (i.e. the path to the dht db)

  - my use case is that I have different instances for different servers (and obviously different dht db files)

c) points a and b could be rectified by placing them in the titlebar of the app

**Comment by chylex** [comment]
The app version is shown in the welcome screen, I don't think it's standard to include the version in the titlebar, but I wouldn't be against it because otherwise the only way to see it is by using Close Database which interrupts tracking, or by opening a second DHT window.

An update check shouldn't be too hard, I already have some code in another project for checking current version against latest release on GitHub. The only thing would be coming up with a good UI for it. Considering the security implications of DHT, I would want to have it disabled by default, but still easily discoverable for people who want it.

Maybe the best idea for a) overall would be a dedicated tab that shows the current version, and has a button to manually check for updates.

For b) having the db filename in the titlebar is pretty standard, so that'd be great to have. The full path is visible in the Database tab, but if by glance you mean taskbar thumbnails, then yea the text field is too small there.
