### ISSUE TITLE
Does not work for mac os

### ISSUE THREAD

**Issue by CarbonationKing** [chylex/Discord-History-Tracker#171]
it doesnt work for mac os despite saying it does

**Comment by TheTechRobo** [comment]
What doesn't work? You need to be more specific.

**Comment by chylex** [comment]
The newest release has correct file permissions, you can run DHT by double-clicking, I verified it works in a VM. The only issue is that since Big Sur, you have to manually approve opening all 4 files in the Security dialog, which is excessive and annoying.

But this is an open-source project that cannot justify spending money and time on doing things the way Apple wants, so if you have an issue with that, you're gonna have to take it up with Apple.
