### ISSUE TITLE
Better Discord Integration and archive recall

### ISSUE THREAD

**Issue by Newsandbuy** [chylex/Discord-History-Tracker#178]
Would it be possible to make a Better Discord Plugin that auto hooks into the desktop app so you dont have to post that script every time you open discord? i use it for legal reasons and it can get pretty annoying to copy the script every time

also the ability for the desktop app to remember the last used archive and auto open it would be nice

**Comment by chylex** [comment]
I'm not planning on integrating it myself. It would be possible to make a plugin that contains the script, but the script contains information for communicating with the app - a port for the integrated server which can change if something is already using the default one, and a randomly generated token that ensures no other application on your computer can communicate with the integrated server (for ex. a malicious website you open in your browser).

To get around this, you can create a shortcut to the DHT app, and configure a custom port, token, and also a path to the database file. On Windows, you can go into the shortcut properties, and modify the Target field to add this additional information. Example:
```
Before:  C:\DiscordHistoryTracker.exe
After:   C:\DiscordHistoryTracker.exe -db "C:\archive.dht" -port 51000 -token yPydUj6BoBbmf8p2q75D
```

This will automatically open `C:\archive.dht`, and set a specific port and token to be always used when you open DHT using this shortcut. If you then copy the tracking script and figure out how to put it into a Better Discord plugin, it'll do what you need.

Tips:
- In Windows, you can hold Shift, right-click the archive file, and then select "Copy as path". This will copy the full path to the file, including quotes as you can see in the example.
- Create your own random token instead of using the example one, you can use a password manager or just type a bunch of random letters and numbers.
