### ISSUE TITLE
Portable version not working on Windows.

### ISSUE THREAD

**Issue by Lifell** [chylex/Discord-History-Tracker#182]
Downloaded the portable version and saw I was missing .NET 5 Runtime. I downloaded both x86 and x64 of "Run console apps" and "Run desktop apps" and tried the dotnet command. It wouldn't register and the application wouldn't run. Also tried to install only the x64 or x86 versions of the .NET 5 Runtime stuff.
![image](https://user-images.githubusercontent.com/26024918/169646777-d31f9128-cd76-47a4-966e-adb83e55d23e.png)
![image](https://user-images.githubusercontent.com/26024918/169646783-402b7a98-43f2-4b58-a0df-ba42a18254be.png)

I'm not a coder but I did notice that it's asking for 5.0.0 while the latest version of the .NET 5 Runtime things is 5.0.17. Could that be the issue?

**Comment by chylex** [comment]
I'll look into it, but you probably don't actually want the portable version. Portable means platform-portable, you can use it if you have an operating system or CPU architecture that I don't provide releases for, like 32-bit Windows or Windows for ARM. If you have 64-bit Windows, you should download the Windows version instead of portable.

**Comment by Lifell** [comment]
Ah, ok. I thought it was the portable version of the application. So nothing gets written to registry or other folders on the OS. Just the folder where the files reside and it launches from.

I will just download the Windows version then, thank you for your reply!

**Comment by chylex** [comment]
All versions have no installers and don't write anything outside the folders you select when saving archives or viewers.

They will save viewers into the operating system's designated temporary folder if you click "Open Viewer", since the files have to exist somewhere to be opened. How temporary files get cleaned up depends on the operating system's, but I will add some automatic cleanup when you exit DHT, so you don't have to rely on the OS to clean them up.

I'll change the "portable" wording to make it clearer.
