### ISSUE TITLE
Viewer: Specify the file to load automatically

### ISSUE THREAD

**Issue by AaronMcHale** [chylex/Discord-History-Tracker#20]
I'd like to host our archive of an old server and the viewer on a secure web server, so it would be nice to have the ability to automatically load the archive when the viewer loads instead of having to load a local file each time.

**Comment by chylex** [comment]
The viewer is fully local so it can't have access to the filesystem. I'll keep the issue open for the future, but keep in mind that any implementation I'd be willing to do would need to download the complete archive anyway which would be a problem for large archives; a fully server-side implementation would require major changes and maintaining two versions of the viewer, so that'd be better as a third-party service.

**Comment by AaronMcHale** [comment]
Thanks for the reply, I was thinking something more simple than it needing to access the file system, for example being able to pass a URL/URI to the log file in the viewer URL e.g. viewer.html#log.txt or viewer.txt?p=log.txt, which in this case log.txt be relative to the viewer.html.  This path could easily be pulled from the URL using JavaScript.

**Comment by chylex** [comment]
That sounds reasonable. Thinking that there should be a confirmation dialog first with the file size, before the viewer starts downloading anything.

**Comment by Beludia** [comment]
Hi there ! Sorry to come here more than one year latter but I would love to have this fonction too, thanks :)

**Comment by chylex** [comment]
I'm adding an experimental feature to the next update, which allows generating a viewer with an embedded archive.

Because the **entire archive is included in the HTML file**, I highly recommend not using it with archives larger than a few megabytes, especially if you plan to host it. I have no idea how any browser would respond to a 50 MB HTML file on a slow connection.

To create an embedded viewer:

1. Wait for the update to be released
2. Add `?embed` to the viewer URL (or open it from the [official website](https://dht.chylex.com/build/viewer.html?embed))
3. Click *Load File* to open your archive
4. Click *Embed File* to generate and download a new viewer file
5. Make sure the generated viewer can be opened and works as expected

Looking for input and bugs. Since the entire process is done inside the browser (and basically performs self-replication), there may be weird browser quirks that end up generating a broken viewer.

**Comment by chylex** [comment]
I would like some input on how well this is working; I think an alternative (potentially more stable) would be to add a build task that embeds the selected file into the viewer, which I might try instead, but it has the disadvantage of requiring the whole build toolchain...

**Comment by chylex** [comment]
The browser-only version of DHT has the experimental embedding feature which should continue working, and the new desktop app version of DHT lets you save viewers with the archive embedded in them, so I consider this closed.
