### ISSUE TITLE
Feature request: Backup All Chats

### ISSUE THREAD

**Issue by Aeternus185** [chylex/Discord-History-Tracker#202]
As title say, backup all chats with one click only.

**Comment by chylex** [comment]
I don't understand the request, please provide more details.

**Comment by TheTechRobo** [comment]
I think he means backing up all servers, channels, DMs, etc.

**Comment by chylex** [comment]
I will let them clarify, but any possibility of backing up multiple servers would need a completely different approach to how DHT detects and navigates between channels.

It might be worth reverse-engineering the Ctrl+K feature, since it can jump to any channel in existence. If it's possible to tell the app to jump to any channel by ID, that would solve a lot of issues with backing up a whole server, possibly allowing for backing up multiple servers automatically.

**Comment by chylex** [comment]
I don't use BetterDiscord and can't really figure out what the linked plugin is doing, can you describe it in more detail?

**Comment by chylex** [comment]
Closing due to no response.
