### ISSUE TITLE
How all merge all channels? what i have to change in the regex...

### ISSUE THREAD

**Issue by PauloDeSouza** [chylex/Discord-History-Tracker#23]
How all merge all channels? what i have to change in the regex...

Sorry, i'm noob at scripting, tried for hours and didnt work... before compiling and after compiling too.. 

(its not a issue btw, just me a try harder) if you could give me where to look i could try again..

**Comment by chylex** [comment]
Hey, are you making a tool that merges all channels in the file itself, or would it be enough to modify the viewer to act as if there was only one channel with all messages?

Modifying the viewer should be easier to do and test, the key file is https://github.com/chylex/Discord-History-Tracker/blob/170c61b3bda771fa569a96b56b7fb18d3d15e3c7/src/renderer/scr.savefile.js (linking to a snapshot in case the file changes in the future).

I'm not 100% sure if this will work, but try:

1. In `getMessages`, return messages from all channels instead of just one
```js
SAVEFILE.prototype.getMessages = function(channel){
  return this.data[channel] || {};
};
```
to...
```js
SAVEFILE.prototype.getMessages = function(channel){
  return this.getAllMessages();
};
```

2. In `getChannelById`, return a "fake" channel instead of the one requested
```js
SAVEFILE.prototype.getChannelById = function(channel){
  return this.meta.channels[channel] || { "id": channel, "name": channel };
};
```
to...
```js
SAVEFILE.prototype.getChannelById = function(channel){
  return { "id": 1, "name": "All Messages" };
};
```

3. In `getChannels`, return a list containing that "fake" channel
```js
SAVEFILE.prototype.getChannels = function(){
  return this.meta.channels;
};
```
to...
```js
SAVEFILE.prototype.getChannels = function(){
  return [ { "id": 1, "name": "All Messages" } ];
};
```

Then run the build script according to instructions, and try viewing the file. Let me know if it throws any errors in the console.

**Comment by PauloDeSouza** [comment]
thanks man, i'm going to try right now!

**Comment by PauloDeSouza** [comment]
it worked perfectly! 

`var SAVEFILE = function(parsedObj){
  var me = this;
  
  me.meta = parsedObj.meta;
  me.meta.users = me.meta.users || {};
  me.meta.userindex = me.meta.userindex || [];
  me.meta.servers = me.meta.servers || [];
  me.meta.channels = me.meta.channels || {};
  
  me.data = parsedObj.data;
};

SAVEFILE.isValid = function(parsedObj){
  return parsedObj && typeof parsedObj.meta === "object" && typeof parsedObj.data === "object";
};

SAVEFILE.prototype.getServer = function(index){
  return this.meta.servers[index] || { "name": "&lt;unknown&gt;", "type": "ERROR" };
};

SAVEFILE.prototype.getChannels = function(){
  return [ { "id": 1, "name": "All Messages" } ];
};

SAVEFILE.prototype.getChannelById = function(channel){
  return { "id": 1, "name": "All Messages" };
};

SAVEFILE.prototype.getUser = function(index){
  return this.meta.users[this.meta.userindex[index]] || { "name": "&lt;unknown&gt;" };
};

SAVEFILE.prototype.getUserById = function(user){
  return this.meta.users[user] || { "name": user };
};

SAVEFILE.prototype.getMessageCount = function(channel){
  return Object.keys(this.getMessages(channel)).length;
};

SAVEFILE.prototype.getAllMessages = function(){
  var messages = {};
  
  UTILS.forEachValue(this.data, messageObject => {
    UTILS.combineObjects(messages, messageObject);
  });
  
  return messages;
};

SAVEFILE.prototype.getMessages = function(channel){
  return this.getAllMessages();
};`

**Comment by PauloDeSouza** [comment]
followed your instructions and now its easier to just scroll down infinitely! 👍 🥇
