### ISSUE TITLE
Shows overwrite prompt

### ISSUE THREAD

**Issue by ShockedCoder** [chylex/Discord-History-Tracker#239]
OS: Linux 6.1.64
DHT: v38

There is currently an overwrite prompt when choosing a file on Linux, in the previous version there were none.
Reporting this as an issue, since I assumed from the update logs that this wasn't an intentional feature.

I'd be happy to provide any extra information.

**Comment by will-ca** [comment]
It appears to use a file selector "Portal" dialog provided by the platform. Since the button is "Open or Create Database", it's the same "Save" dialog for both creating new archives and opening existing ones, which, as provided by the desktop environment outside of DHT's control, defaults to confirming when you select an existing file.

Gave me a couple seconds' pause too when I saw it, before I realized what was likely happening.

**Comment by ShockedCoder** [comment]
Yeah, I understand that it most likely wouldn't overwrite the archive database.

I wasn't planning on creating an issue until I saw that this is an unintended effect, so I thought it'd be best to bring it to light. I don't mind this, but the prompt is unsettling each time I see it, even though I know nothing's gonna happen.

**Comment by chylex** [comment]
The UI library I'm using, at least on KDE, uses XDG Desktop Portal which does not support turning off the overwrite prompt. https://github.com/flatpak/xdg-desktop-portal/issues/706
