### ISSUE TITLE
Can't download larger attachments

### ISSUE THREAD

**Issue by espressoelf** [chylex/Discord-History-Tracker#256]
I've backed up some rather media-heavy servers and noticed that larger attachments just won't finish downloading. It seems that the download connection of an individual file gets closed after about 30 seconds. The download doesn't fail, i.e. doesn't get listed as "failed" in the app, and DHT doesn't resume/retry or continue downloading at all.

It also seems that there are 4 concurrent downloads. Would it be possible to make the number of concurrent downloads adjustable? The same goes for the timeout, if there's any.

I'm using the Desktop App (v41.1)/win-x64.zip/DiscordHistoryTracker.exe on Windows 10 (22H2) to download. I've used Windows' Performance Monitor and Sysinternals TCPView to check whether it's still downloading or not.

**Comment by chylex** [comment]
There is a 30s timeout I intended to be an idle timeout, if it's closing the connection during an active download then it's a bug; good catch.

I want to make the number of concurrent downloads adjustable in the future, but if the reason why you want to adjust it is because of large attachments using too much memory, then a better solution would be to save the attachments as temporary files (that's the plan anyway, I just don't have time). Usually files are very small so I picked 4 concurrent downloads as the default, if it was fewer then there'd be a lot more time spent waiting for downloads to start.

**Comment by espressoelf** [comment]
The number of concurrent downloads is a good one and being able to change it would be (very) low priority for me if the downloads stopped because of the idle timeout. Wouldn't even need to be in the GUI, a command-line switch is fine, too.

I've never had any problems with memory usage. Thanks for your efforts, I really love DHT so far! <3

**Comment by chylex** [comment]
Released v41.2.
