### ISSUE TITLE
"save viewer" is missing

### ISSUE THREAD

**Issue by alexmonkey05** [chylex/Discord-History-Tracker#263]
![image](https://github.com/user-attachments/assets/76ae9fd1-d8c8-4eb5-b3b2-c847404a7ecd)
   
### I can't see "save viewer" button
![image](https://github.com/user-attachments/assets/9ae49ed2-fc11-4cb4-9f73-874e43c2fac7)
   
### how can I export saved messages to html file?

**Comment by chylex** [comment]
You cannot, see discussion https://github.com/chylex/Discord-History-Tracker/discussions/246.

If you need the Save Viewer option, you need to use version 41.2.

Keep in mind that Save Viewer has many limitations, including the fact that all attachments and embeds in every exported HTML viewer are broken, because Discord links now expire. The only way you can keep attachments and embeds is by downloading them, which has never worked with Save Viewer.

**Comment by alexmonkey05** [comment]
oh thanks
