### ISSUE TITLE
Support for auto tracking

### ISSUE THREAD

**Issue by bluefiberbread** [chylex/Discord-History-Tracker#37]
Will there be support to automatically track new messages without combining and downloading over and over again?

**Comment by chylex** [comment]
All data is stored in memory, so if you close the tab without downloading the archive, it will be lost. Since it's just a bookmark script, it doesn't have access to files where it could automatically store the data.

Right now I'm not planning to make DHT into a browser addon/userscript which would support this, so I'll close the issue. If I do eventually make DHT an addon/userscript, I will keep this in mind.
