### ISSUE TITLE
Pause tracking after reaching end of a Category 

### ISSUE THREAD

**Issue by COLDsteem** [chylex/Discord-History-Tracker#52]
Earlier versions of this app would stop after reaching the end of a Category. Right now, Tracking is continuing on to the next Category, until all Categories on the server are tracked.

Adding another group of radio-buttons with the title "After reaching the end of a Category..."  in Settings menu would solve this problem, and gave users a choice.

Btw, thanks for the app, it's a life saver! Great work!

**Comment by chylex** [comment]
Stopping after reaching a category was a bug because it couldn't find the next channel (related, I don't even know how the detection works with collapsed categories).

I don't really want to touch the feature, PRs are open if someone wants to have a go (let me know here first to discuss the actual implementation), but if Discord breaks anything related to switching to the next channel again, it's probably not coming back.

**Comment by COLDsteem** [comment]
Thanks for the reply! I'll close the issue now, since, it turned out it's not an issue! :)  Though, it would've been nice if somebody did implement the suggested option in the Settings as well... :)

On a side note, it seems that Tracking is not working properly, just used it, and it won't stop or switch to next channel after reaching a previously saved message... perhaps I should open a separate issue thread for this one.

**Comment by chylex** [comment]
Already fixed, releasing an update in the next few hours.
