### ISSUE TITLE
Investigate distribution as a Userscript

### ISSUE THREAD

**Issue by ssokolow** [chylex/Discord-History-Tracker#54]
As I understand it, the problem with making Discord History Tracker a bookmarklet is that bookmarklets don't currently get an exemption from Content Security Policies.

Have you considered making DHT into a Userscript? Userscript hosts like [Greasemonkey 4](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/) (Firefox-only), [Violentmonkey](https://violentmonkey.github.io/get-it/) (fork of Greasemonkey 3), and [Tampermonkey](https://tampermonkey.net/) (closed-source) are geared for working around just that kind of issue and basically provide a superset of what bookmarklets can do.

(It's a superset of the features available in a bookmarklet, you can still host them anywhere, just by offering a raw link to a file named `something.user.js`, and there's still no requirement to submit to a central authority for signing like with a browser extension... though the [Greasyfork](http://greasyfork.org/), hosting site, which I recommend, does require you to submit un-minified code and will do some basic automated checks to catch shady business, like `@require`-ing scripts from URLs not on their whitelist of places that do minimal moderation.)

It also has the benefit that you can offer your users the option of automated updates. Userscript hosts support that and typically allow users to enable or disable them on a per-script basis. (I strongly recommend letting Greasyfork handle this if you want it, since it'll ensure that all the update-related metadata is set correctly and hold back any updates which don't pass its safety checks.)

I tried wrapping your code up in the boilerplate for a Userscript and it almost works as-is:

```js
// ==UserScript==
// @name     Discord History Tracker
// @version  1
//
// @require      https://greasemonkey.github.io/gm4-polyfill/gm4-polyfill.js
//
// @match       https://discordapp.com/*
//
// @grant       GM_registerMenuCommand
// @grant       GM.registerMenuCommand
// ==/UserScript==

function init() {
    // YOUR CODE HERE
}

(async function() {
    GM.registerMenuCommand("Load Discord History Tracker", init);
})();
```

(Yes, you technically don't need the async function, but I find it's a good way to demonstrate how to use the Greasemonkey 4-compatible Promise-based APIs in a more blocking-like fashion. As for `@grant`ing `GM_registerMenuCommand`, it's used by `gm4-polyfill.js` to implement `GM.registerMenuCommand` on userscript hosts that provide Greasemonkey 3-style blocking APIs.)

Specifically, everything I tried worked, except that when I chose "Start Tracking" the count of found messages didn't increase as it loaded and scrolled and loaded and scrolled.

That kind of "everything Just Works™ except this one little thing" mismatch typically indicates that the problem lies in one of the minor behavioural differences between actual DOM objects and the proxy objects that a Userscript host (or browser extension) receives when you use `@grant` flags other than `@grant none` and it has to run the script in a separate sandbox from the site code to safely expose the privileged APIs.

I don't have time to try it right now, but the fix should be as trivial as doing one of the following things:

1. Identify the line that behaves differently when run in a userscript without `@grant none` and fix it. (It should have to do with your code trying to manipulate the DOM object directly rather than calling an appropriate getter/setter method. For example, two DOM queries aren't guaranteed to return the same proxy for the same object, so you need to manipulate attributes or properties using the DOM API setters and getters to make sure they get set on the underlying DOM object.)
2. Set `@grant none` in the userscript metadata block and, rather than using `GM.registerMenuCommand`, inject your own "Load Discord History Tracker" button into the page. (The nice thing about `GM.registerMenuCommand` is that it stays out of the way. Tampermonkey and Violentmonkey add the entry to the menu hanging off their toolbar button and, when `gm4-polyfill.js` encounters Greasemonkey 4, it takes advantage of Firefox's support for letting sites add custom entries to the context menu.)
3. Set `@grant none` and just have the DHT toolbar *always* load itself after the page finishes loading.

**NOTE:** When using `GM.registerMenuCommand` with Greasemonkey 4, you need to use Firefox's Shift+RightClick feature for forcibly bypassing site-defined context menus to display the browser-provided one.

**Comment by chylex** [comment]
I initially made it a bookmarklet so that it wasn't dependent on any addons, because then it couldn't easily work in the Discord app itself, and this way there'd only be a single version of the code you can run either in a browser or the app (and Firefox could install bookmarklets with a special `<a>` tag, which was super convenient). Unfortunately the bookmark part doesn't work anymore, there is a [https://bugzilla.mozilla.org/show_bug.cgi?id=1478037](bug report) for FF that might get resolved, I'll have to look into how other browsers work nowadays.

Anyway, I agree that a userscript would have been a better idea and I think I can make it so a single script can be both used as a userscript and pasted into the console to work in the app.

I suspect the problem with not finding messages is because Discord uses React, and DHT heavily relies on the internal state that's stored directly in the DOM element objects. I think the only way to get that is through `unsafeWindow`.

I'll look into it at some point, there's a ton of issues opened in the repo right now and I don't have time to deal with that, but one day I'll make some time to go through everything.
