### ISSUE TITLE
Export attatched file URLs to list?

### ISSUE THREAD

**Issue by ewkytpmv** [chylex/Discord-History-Tracker#63]
Hi, really love this project but I like to have complete archives so I was wondering if there's any chance of eventually seeing a feature that allows you to export all cdn.discordapp.com links to a .txt list for downloading with wget and possibly an option to redirect the URLs in the archive to the local files (e.g. replacing https://cdn.discordapp.com/foo/bar/image.jpg with file:///C:/User/Foo/DHT/foo/bar/image.png)? It would be a big help for me and likely many others.
Thanks!

**Comment by OnceDot** [comment]
I'm working on this. See you later !

**Comment by chylex** [comment]
For command line processing, I looked around and found [jq](https://stedolan.github.io/jq/). Here's an example filter that outputs a list of attachment URLs from an archive file:

`jq --raw-output '.data | .[] | .[] | select(.a) | .a | .[] | .url'`

Then you can filter images, download, and update the URLs (which should be possible with `jq` again, or a simple search/replace).

Any sorts of export/conversion features won't be included directly into DHT, since the archive format is simple JSON with a structure [described in source code](https://github.com/chylex/Discord-History-Tracker/blob/master/src/tracker/savefile.js), so it can be fairly easily manipulated with scripting/cli tools.
