### ISSUE TITLE
Record displayed nicknames and avatars, specifically for webhooks

### ISSUE THREAD

**Issue by evg-zhabotinsky** [chylex/Discord-History-Tracker#64]
Some bots post their messages through webhooks. IRC<->Discord relay bots do that, for example.
The displayed nickname and avatar can be different for every post, and neither is currently saved by DHT, it seems. (Only tried the copy-paste version from the site.)

**Comment by AnastasiaDunbar** [comment]
Also not just user avatars but what about server icons and group icons as well?

**Comment by chylex** [comment]
That is a limitation of the way DHT saves users. A workaround could be to detect bot messages and register each nickname as a new user, but then it wouldn't be possible to use the discord user ID since each ID can only have 1 nickname in the archive format.

Avatars/icons/images/anything else that isn't plain text is never going to be saved, DHT is not the right tool for that.

**Comment by AnastasiaDunbar** [comment]
Not even the URLs redirecting to the profile pictures?

**Comment by Legend-of-iPhoenix** [comment]
Recording user avatars matters much less than recording the webhook name, the latter is often essential for understanding conversations with linkers like matterbridge, etc.

**Comment by chylex** [comment]
I'll take a look at how username switching works on Discord's end at some point, and see how easy it would be to support this.

**Comment by chylex** [comment]
Closing in favor of #247.
