### ISSUE TITLE
Read messages' date of edit

### ISSUE THREAD

**Issue by AnastasiaDunbar** [chylex/Discord-History-Tracker#66]
It would provide more context.
If you could also reread the conversation and include before-and-after edits (using their IDs), that would be great (along with #28).
`div[class^="markup-"] time[role="note"]`→`.dateTime`.

**Comment by chylex** [comment]
I'll add an edit timestamp, but not planning to show a before/after edit, especially since DHT isn't really intended to be running constantly nor will it see any channels but the one that's shown on screen, so there's a very low chance it could even catch an edit before it's made.

**Comment by COLDsteem** [comment]
Is there a way for DHT to Load an archive, and then go through the whole channel again, and append edited messages, or note if the message was deleted in the mean time? Like, go through old messages in the archive and look for edits and deletions, and denote that by adding the edited message in the original message body, and noting deleted message by, say, color.

**Comment by chylex** [comment]
Tracking edited messages replaces the old message. Deleted messages just continue existing, they could possibly be detected if DHT loaded 2 previously existing messages surrounding a message which got deleted since, but it'd just be a heuristic that could fail (for ex. with mass-deleted messages).

I think your best option, if you know any scripting/programming language, is to create a second archive of the server, and then compare it with the previous one to find messages with the same ID but different text and edit time, and messages which only exist in the previous archive. The archive is just standard JSON format, its structure is described in a [source code comment](https://github.com/chylex/Discord-History-Tracker/blob/master/src/tracker/savefile.js).

**Comment by AnastasiaDunbar** [comment]
I bet there'd be users editing their messages into soft hyphens (“­”).

**Comment by chylex** [comment]
If you don't re-track an edited message, it won't be updated in the archive. If you set autoscroll to stop or switch channels after seeing a previously seen message, it will still re-track up to 99 messages before the last one, but anything older won't be updated.

If you're tracking the kind of server where people constantly edit messages, best solution would be to keep older versions of the archives.
