### ISSUE TITLE
Download new message from the time of running script in console / opening page

### ISSUE THREAD

**Issue by Firecatmon** [chylex/Discord-History-Tracker#68]
Basically I'd suggest a feature which downloads new messages from the time you toggle a checkbox in the settings menu? As in when you toggle it on, it will download every NEW message sent after you toggled, then you can leave discord or your browser open and it will keep adding on to a file which you specify. 

So how you would use it is:
After you choose the channel you would leave the browser running and whenever someone sends a message in that channel the program will save it.

Does that make any sense?

**Comment by COLDsteem** [comment]
That would be awesome! Some kind of real-time backup, saving messages on the fly, or after a few minutes or a few hours, depending on the user preferences. Once the script reaches old messages, it would wait for new ones, and check later. 

Perhaps the script could do that automatically once started and preferred settings selected. Backup all the channel's messages in one file, or the whole server depending on the user's settings.

Also, this would require adding and combining old backed up files into the one new file.

**Comment by chylex** [comment]
Not sure why you'd need to only save new messages. If you turn off autoscroll you can just leave it running and it'll save any message it sees + the 50 messages that were already displayed, you still need to save the archive manually though.

Right now there's a bug where DHT tracks your unsent messages and ends up duplicating them because the server gives them a different ID. I'll address that in the next update.

**Comment by COLDsteem** [comment]
Yeah, autoscroll off... I've totally forgotten about that option. Mostly used DHT post-fact, for, more like, archiving... so I kept autoscroll ticked on all the time. 
Thanks!

**Comment by chylex** [comment]
The bug with tracking unseen messages is fixed, so disabling autoscroll should do.
