### ISSUE TITLE
Order of archived channels is not correct

### ISSUE THREAD

**Issue by COLDsteem** [chylex/Discord-History-Tracker#78]
The order of archived channels is not reflecting the order of my server channels. In the viewer, archived channels are ordered alphabetically, where my server channels are ordered by date (for some categories), or reordered by over time (for most other categories).

**Comment by COLDsteem** [comment]
OK, never mind, it turned out it's intentional:

> Ended up deciding to sort channels by name (grouped by type and server first). Won't be as nice in some cases, but at least it's consistent.

 _Originally posted by @chylex in https://github.com/chylex/Discord-History-Tracker/issues/11#issuecomment-528701999_

It would be nice, if we could have an option to view original channel order (and Categories).

**Comment by chylex** [comment]
Before the update, channels and servers used to be ordered based on when you started tracking them, they were never ordered the same way they are in the server. Same with DMs and groups, but there it was even more confusing since the order of DMs changes a lot but it'd never change in the viewer.

Ultimately I decided to sort by type/server and then alphabetically, because as I mentioned it's consistent, but also for technical reasons:

 - DHT doesn't have a good view of channel order; the only time it attempts to list channels in order is for the *Select next channel after reaching top/last saved message* feature, which is more prone to breaking by Discord updates than the rest of DHT because it relies on the HTML layout
 - If a channel is not visible on the screen, i.e. inside a collapsed category or above/below the screen and requires scrolling, it's as if it didn't exist at all

Overall it'd make keeping track of order a lot more difficult because DHT can't see every channel that exists on the server, and therefore can't tell if certain channels have moved, were deleted, or are just hidden, plus tracking an unseen channel would require a reference point for the order.

If someone finds an internal structure from which DHT can get all server channels and user DMs/groups even if they're not visible, I'll most likely support original channel order.

**Comment by COLDsteem** [comment]
Yeah, that'd be cool if someone finds a way, mostly because of server channels, since, for me personally, DMs are not an issue, since I'm archiving them individually as a separate archive for every private chat with a user. 
As for the server channels, I archive by Categories with each category containing multiple channels, so correct channel ordering would be very helpful.

**Comment by chylex** [comment]
#102 made it possible to order channels by their real order. It will still probably break in cases where a new channel is added to a server and the following channels aren't re-tracked, but in most cases it should be fine.
