### ISSUE TITLE
GDPR & Privacy

### ISSUE THREAD

**Issue by throwaway88888** [chylex/Discord-History-Tracker#96]
As someone who lives in Europe and understands the international nature of Discord's userbase, have you considered GDPR and other legal implications? By creating this tool with no restrictions on usage or any built-in method of requesting permission from server members, are DHT and its users not in direct violation of GDPR? Aren't you as the developer also liable, by intentionally making it in a way that does not comply while making it available to EU users and usable on EU citizens? 

I also wonder what Discord think of you publicly making such a questionable tool that has no real purpose except stalking people and invading everyone's privacy? I mean, the disclaimer on your website is cute, but obviously meaningless and a transparently pathetic attempt at covering your own ass. 

The fact people are actually sad and desperate enough to use this makes me laugh. Are you that lacking in human interaction that you have to resort this?

**Comment by chylex** [comment]
Keeping chat logs for personal use is exempt from GDPR. If it wasn't, it would be impractical - you cannot stop someone from say, recording their screen and putting a weight on the keyboard to scroll up, which is similar to what DHT does.

Since this is clearly a new troll account and has immediately resorted to personal attacks, I assume there's no intention of a real discussion and will be deleting the issue once you had a chance to read it.
